// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccumulatedAmountsModel
    {
        /// <summary>
        /// Initializes a new instance of the AccumulatedAmountsModel class.
        /// </summary>
        public AccumulatedAmountsModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccumulatedAmountsModel class.
        /// </summary>
        public AccumulatedAmountsModel(double depositTotalFiat, double deposit30DaysFiat, double deposit1DayFiat, double depositTotalNonFiat, double deposit30DaysNonFiat, double deposit1DayNonFiat, double withdrawalTotalFiat, double withdrawal30DaysFiat, double withdrawal1DayFiat, double withdrawalTotalNonFiat, double withdrawal30DaysNonFiat, double withdrawal1DayNonFiat)
        {
            DepositTotalFiat = depositTotalFiat;
            Deposit30DaysFiat = deposit30DaysFiat;
            Deposit1DayFiat = deposit1DayFiat;
            DepositTotalNonFiat = depositTotalNonFiat;
            Deposit30DaysNonFiat = deposit30DaysNonFiat;
            Deposit1DayNonFiat = deposit1DayNonFiat;
            WithdrawalTotalFiat = withdrawalTotalFiat;
            Withdrawal30DaysFiat = withdrawal30DaysFiat;
            Withdrawal1DayFiat = withdrawal1DayFiat;
            WithdrawalTotalNonFiat = withdrawalTotalNonFiat;
            Withdrawal30DaysNonFiat = withdrawal30DaysNonFiat;
            Withdrawal1DayNonFiat = withdrawal1DayNonFiat;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DepositTotalFiat")]
        public double DepositTotalFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Deposit30DaysFiat")]
        public double Deposit30DaysFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Deposit1DayFiat")]
        public double Deposit1DayFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DepositTotalNonFiat")]
        public double DepositTotalNonFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Deposit30DaysNonFiat")]
        public double Deposit30DaysNonFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Deposit1DayNonFiat")]
        public double Deposit1DayNonFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WithdrawalTotalFiat")]
        public double WithdrawalTotalFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Withdrawal30DaysFiat")]
        public double Withdrawal30DaysFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Withdrawal1DayFiat")]
        public double Withdrawal1DayFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WithdrawalTotalNonFiat")]
        public double WithdrawalTotalNonFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Withdrawal30DaysNonFiat")]
        public double Withdrawal30DaysNonFiat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Withdrawal1DayNonFiat")]
        public double Withdrawal1DayNonFiat { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
