// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Limitations;
    using Lykke.Service.Limitations.Client;
    using Lykke.Service.Limitations.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClientData
    {
        /// <summary>
        /// Initializes a new instance of the ClientData class.
        /// </summary>
        public ClientData()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientData class.
        /// </summary>
        public ClientData(IList<RemainingLimitation> remainingLimits = default(IList<RemainingLimitation>), IList<CashOperation> cashOperations = default(IList<CashOperation>), IList<CashOperation> cashTransferOperations = default(IList<CashOperation>), IList<CurrencyOperationAttempt> operationAttempts = default(IList<CurrencyOperationAttempt>))
        {
            RemainingLimits = remainingLimits;
            CashOperations = cashOperations;
            CashTransferOperations = cashTransferOperations;
            OperationAttempts = operationAttempts;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remainingLimits")]
        public IList<RemainingLimitation> RemainingLimits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashOperations")]
        public IList<CashOperation> CashOperations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashTransferOperations")]
        public IList<CashOperation> CashTransferOperations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operationAttempts")]
        public IList<CurrencyOperationAttempt> OperationAttempts { get; set; }

    }
}
