// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClientTier
    {
        /// <summary>
        /// Initializes a new instance of the ClientTier class.
        /// </summary>
        public ClientTier()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientTier class.
        /// </summary>
        public ClientTier(string clientId, string tierId)
        {
            ClientId = clientId;
            TierId = tierId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TierId")]
        public string TierId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ClientId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ClientId");
            }
            if (TierId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TierId");
            }
        }
    }
}
