// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Limitations;
    using Lykke.Service.Limitations.Client;
    using Lykke.Service.Limitations.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CurrencyOperationAttempt
    {
        /// <summary>
        /// Initializes a new instance of the CurrencyOperationAttempt class.
        /// </summary>
        public CurrencyOperationAttempt()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CurrencyOperationAttempt class.
        /// </summary>
        /// <param name="operationType">Possible values include: 'CardCashIn',
        /// 'CardCashOut', 'CryptoCashIn', 'CryptoCashOut', 'SwiftTransfer',
        /// 'SwiftTransferOut'</param>
        public CurrencyOperationAttempt(string clientId = default(string), double? amount = default(double?), string asset = default(string), string operationType = default(string), System.DateTime? dateTime = default(System.DateTime?))
        {
            ClientId = clientId;
            Amount = amount;
            Asset = asset;
            OperationType = operationType;
            DateTime = dateTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asset")]
        public string Asset { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'CardCashIn', 'CardCashOut',
        /// 'CryptoCashIn', 'CryptoCashOut', 'SwiftTransfer',
        /// 'SwiftTransferOut'
        /// </summary>
        [JsonProperty(PropertyName = "operationType")]
        public string OperationType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateTime")]
        public System.DateTime? DateTime { get; set; }

    }
}
