// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IClientTierLogRecord
    {
        /// <summary>
        /// Initializes a new instance of the IClientTierLogRecord class.
        /// </summary>
        public IClientTierLogRecord()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IClientTierLogRecord class.
        /// </summary>
        public IClientTierLogRecord(string oldTierId, string newTierId, string changer, System.DateTime changeDate)
        {
            OldTierId = oldTierId;
            NewTierId = newTierId;
            Changer = changer;
            ChangeDate = changeDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OldTierId")]
        public string OldTierId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NewTierId")]
        public string NewTierId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Changer")]
        public string Changer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChangeDate")]
        public System.DateTime ChangeDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (OldTierId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "OldTierId");
            }
            if (NewTierId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "NewTierId");
            }
            if (Changer == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Changer");
            }
        }
    }
}
