// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for LimitationPeriod.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LimitationPeriod
    {
        [EnumMember(Value = "Day")]
        Day,
        [EnumMember(Value = "Month")]
        Month
    }
    internal static class LimitationPeriodEnumExtension
    {
        internal static string ToSerializedValue(this LimitationPeriod? value)
        {
            return value == null ? null : ((LimitationPeriod)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this LimitationPeriod value)
        {
            switch( value )
            {
                case LimitationPeriod.Day:
                    return "Day";
                case LimitationPeriod.Month:
                    return "Month";
            }
            return null;
        }

        internal static LimitationPeriod? ParseLimitationPeriod(this string value)
        {
            switch( value )
            {
                case "Day":
                    return LimitationPeriod.Day;
                case "Month":
                    return LimitationPeriod.Month;
            }
            return null;
        }
    }
}
