// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for LimitationType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LimitationType
    {
        [EnumMember(Value = "CardCashIn")]
        CardCashIn,
        [EnumMember(Value = "CardCashOut")]
        CardCashOut,
        [EnumMember(Value = "CryptoCashIn")]
        CryptoCashIn,
        [EnumMember(Value = "CryptoCashOut")]
        CryptoCashOut,
        [EnumMember(Value = "SwiftCashIn")]
        SwiftCashIn,
        [EnumMember(Value = "SwiftCashOut")]
        SwiftCashOut,
        [EnumMember(Value = "OverallCashIn")]
        OverallCashIn,
        [EnumMember(Value = "OverallCashOut")]
        OverallCashOut,
        [EnumMember(Value = "CardAndSwiftCashIn")]
        CardAndSwiftCashIn
    }
    internal static class LimitationTypeEnumExtension
    {
        internal static string ToSerializedValue(this LimitationType? value)
        {
            return value == null ? null : ((LimitationType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this LimitationType value)
        {
            switch( value )
            {
                case LimitationType.CardCashIn:
                    return "CardCashIn";
                case LimitationType.CardCashOut:
                    return "CardCashOut";
                case LimitationType.CryptoCashIn:
                    return "CryptoCashIn";
                case LimitationType.CryptoCashOut:
                    return "CryptoCashOut";
                case LimitationType.SwiftCashIn:
                    return "SwiftCashIn";
                case LimitationType.SwiftCashOut:
                    return "SwiftCashOut";
                case LimitationType.OverallCashIn:
                    return "OverallCashIn";
                case LimitationType.OverallCashOut:
                    return "OverallCashOut";
                case LimitationType.CardAndSwiftCashIn:
                    return "CardAndSwiftCashIn";
            }
            return null;
        }

        internal static LimitationType? ParseLimitationType(this string value)
        {
            switch( value )
            {
                case "CardCashIn":
                    return LimitationType.CardCashIn;
                case "CardCashOut":
                    return LimitationType.CardCashOut;
                case "CryptoCashIn":
                    return LimitationType.CryptoCashIn;
                case "CryptoCashOut":
                    return LimitationType.CryptoCashOut;
                case "SwiftCashIn":
                    return LimitationType.SwiftCashIn;
                case "SwiftCashOut":
                    return LimitationType.SwiftCashOut;
                case "OverallCashIn":
                    return LimitationType.OverallCashIn;
                case "OverallCashOut":
                    return LimitationType.OverallCashOut;
                case "CardAndSwiftCashIn":
                    return LimitationType.CardAndSwiftCashIn;
            }
            return null;
        }
    }
}
