// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for LimitationType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LimitationType
    {
        [EnumMember(Value = "CardCashIn")]
        CardCashIn,
        [EnumMember(Value = "CryptoCashOut")]
        CryptoCashOut,
        [EnumMember(Value = "CardAndSwiftCashIn")]
        CardAndSwiftCashIn
    }
    internal static class LimitationTypeEnumExtension
    {
        internal static string ToSerializedValue(this LimitationType? value)
        {
            return value == null ? null : ((LimitationType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this LimitationType value)
        {
            switch( value )
            {
                case LimitationType.CardCashIn:
                    return "CardCashIn";
                case LimitationType.CryptoCashOut:
                    return "CryptoCashOut";
                case LimitationType.CardAndSwiftCashIn:
                    return "CardAndSwiftCashIn";
            }
            return null;
        }

        internal static LimitationType? ParseLimitationType(this string value)
        {
            switch( value )
            {
                case "CardCashIn":
                    return LimitationType.CardCashIn;
                case "CryptoCashOut":
                    return LimitationType.CryptoCashOut;
                case "CardAndSwiftCashIn":
                    return LimitationType.CardAndSwiftCashIn;
            }
            return null;
        }
    }
}
