// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Limitations;
    using Lykke.Service.Limitations.Client;
    using Lykke.Service.Limitations.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RemainingLimitation
    {
        /// <summary>
        /// Initializes a new instance of the RemainingLimitation class.
        /// </summary>
        public RemainingLimitation()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RemainingLimitation class.
        /// </summary>
        /// <param name="limitationType">Possible values include: 'CardCashIn',
        /// 'CryptoCashOut', 'CardAndSwiftCashIn'</param>
        public RemainingLimitation(string limitationType = default(string), string asset = default(string), double? remainingAmount = default(double?))
        {
            LimitationType = limitationType;
            Asset = asset;
            RemainingAmount = remainingAmount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'CardCashIn',
        /// 'CryptoCashOut', 'CardAndSwiftCashIn'
        /// </summary>
        [JsonProperty(PropertyName = "limitationType")]
        public string LimitationType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remainingAmount")]
        public double? RemainingAmount { get; set; }

    }
}
