// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Limitations;
    using Lykke.Service.Limitations.Client;
    using Lykke.Service.Limitations.Client.AutorestClient;
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SwiftTransferLimitation
    {
        /// <summary>
        /// Initializes a new instance of the SwiftTransferLimitation class.
        /// </summary>
        public SwiftTransferLimitation()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SwiftTransferLimitation class.
        /// </summary>
        public SwiftTransferLimitation(string asset, decimal minimalWithdraw)
        {
            Asset = asset;
            MinimalWithdraw = minimalWithdraw;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimalWithdraw")]
        public decimal MinimalWithdraw { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Asset == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Asset");
            }
            if (Asset != null)
            {
                if (Asset.Length < 1)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Asset", 1);
                }
            }
        }
    }
}
