// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Limitations.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TierRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the TierRequestModel class.
        /// </summary>
        public TierRequestModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TierRequestModel class.
        /// </summary>
        public TierRequestModel(Tier tier, string changer)
        {
            Tier = tier;
            Changer = changer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Tier")]
        public Tier Tier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Changer")]
        public string Changer { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Tier == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Tier");
            }
            if (Changer == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Changer");
            }
            if (Tier != null)
            {
                Tier.Validate();
            }
        }
    }
}
